FROM jenkins/jenkins:2.440.1-jdk17
USER root
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
RUN apt-get update && apt-get install -y lsb-release

RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
  https://download.docker.com/linux/debian/gpg
RUN echo "deb [arch=$(dpkg --print-architecture) \
  signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
  https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

RUN apt-get update && apt-get install -y docker-ce-cli

EXPOSE 8080
COPY ./ /project
COPY /vagrant/keys/id_rsa /root/.ssh/
RUN chmod 600 /root/.ssh/id_rsa
COPY /vagrant/keys/id_rsa.pub /root/.ssh/
COPY /vagrant/Docker-compose.yml /

RUN jenkins-plugin-cli --plugins "blueocean docker-workflow"